import React, {useState} from 'react';
import OtherNameTypes from './components/OtherNameTypes';


function Data(){
//	const [value1, setValue1] = useState(null);
//	const [value2, setValue2] = useState(null);
	const [value3, setValue3] = useState("MIDDLE_NAME");
	const [value4, setValue4] = useState("");	
	const [value5, setValue5] = useState("ALIAS");
	
	const [listOfItems, setListOfItems] = useState([{name:"Item Six", value:""}, {name:"Item Seven",value:""}, {name:"Item Eight",value:""}, {name:"Item Nine",value:""}, {name:"Item Ten",value:""}]);

	const onChangeOfValue5Handler = (event) =>{
		alert("event-id=" + event.target.id);
		alert("event-value=" + event.target.value);
	}
	
	const onChangeOfListedItem = (event) =>{
		const targetId = event.target.id;
		const targetValue = event.target.value;
		const update = (item) => {item.value = targetValue; return item};
		const updateIf = (item) => item.name === targetId ? update(item) : item;
		const updatedItems = listOfItems.map((item) => updateIf(item) );
		setListOfItems(updatedItems);
	}
	
	return(
		<table>
			<tbody>
{/** Disabled to reduce noise generated by warnings
				<tr>
					<td>Item One</td>
					<td><OtherNameTypes id="one" valueSetter={setValue1} /> </td>
					<td>Not Initialised. i.e. currentValue not specified at all</td>
					<td> The value selected is {value1} .</td>
				</tr>
				<tr>
					<td>Item Two</td>
					<td><OtherNameTypes id="two" currentValue={value2} valueSetter={setValue2} /> </td>
					<td>Initialised currentValue with value2 which is null </td>
					<td> The value selected is {value2} .</td>
				</tr>
 */}
				<tr>
					<td>Item Three</td>
					<td><OtherNameTypes id="three" currentValue={value3} valueSetter={setValue3}/> </td>
					<td>Initialised currentValue with value3 which was initialised with "MIDDLE_NAME" </td>
					<td> The value selected is {value3} .</td>
				</tr>
				<tr>
					<td>Item Four</td>
					<td><OtherNameTypes id="four" currentValue={value4} valueSetter={setValue4} /> </td>
					<td>Initialised currentValue with value4 which was initialised with "", i.e. an empty string</td>
					<td> The value selected is {value4} .</td>
				</tr>		
				<tr>
					<td>Item Five</td>
					<td><OtherNameTypes id="five" currentValue={value5} valueSetter={setValue5} onChange={onChangeOfValue5Handler} /> </td>
					<td>Initialised currentValue with value5 which was initialised with "ALIAS"</td>
					<td> The value selected is {value5} .</td>
				</tr>
				
				{listOfItems.map((item) =>
					<tr key={item.name}>
						<td>{item.name}</td>
						<td><OtherNameTypes id={item.name} currentValue={item.value} onChange={onChangeOfListedItem} /> </td>
						<td>Initialised with empty string</td>
						<td> The value selected is {item.value} .</td>
					</tr>
				)}							
			</tbody>
		</table>

	);
};

export default Data;